# Generated by Django 6.0 on 2026-02-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hoteluser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='buisness_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
