# Generated by Django 6.0 on 2026-02-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hotelvendor_buisness_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hoteluser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
