# Generated by Django 6.0 on 2026-02-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hoteluser_is_vendor_alter_hoteluser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='buisness_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
